### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by lndicaa** [samsesh/SocialBox-Termux#13]
ig - tor not working
twitter - not working 
fb not working 
gmail no work at all

**Comment by samsesh** [comment]
Check my other repository's:)

**Comment by raminam6488** [comment]
> ig - tor not working
> twitter - not working
> fb not working
> gmail no work at all

**Comment by raminam6488** [comment]
@raminam6488

**Comment by raminam6488** [comment]
hi github chetoriyh

**Comment by peepeekk** [comment]
in
