### ISSUE TITLE
Error in gmail bruteforce.

### ISSUE THREAD

**Issue by RISHI210505** [samsesh/SocialBox-Termux#23]
This Error is shown 
File "/data/data/com.termux/files/home/SocialBox-Termux/Gemail-Hack/gemailhack.py", line 8
    print '================================================='
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('=================================================')?
How to resolve it.

**Comment by samsesh** [comment]
use python2

**Comment by samsesh** [comment]
try this
python2 /data/data/com.termux/files/home/SocialBox-Termux/Gemail-Hack/gemailhack.py
