### ISSUE TITLE
time

### ISSUE THREAD

**Issue by cheetaco** [samsesh/SocialBox-Termux#26]
why it took so long for the time? is it normal or not?

**Comment by samsesh** [comment]
who much ?

**Comment by SanpreetTawde73** [comment]
![Screenshot_2021-09-16-16-14-19-777_com.termux.jpg](https://user-images.githubusercontent.com/87819107/133598456-69a77b47-b305-468c-9662-6e76995f8a1e.jpg)

It's not working sir when I chose 3 or 5 option

**Comment by samsesh** [comment]
Run this code 

`apt install openssl -y`

And tryagin
