### ISSUE TITLE
Wordlist path

### ISSUE THREAD

**Issue by Smok3snight** [samsesh/SocialBox-Termux#27]
Please am sorry but am new to this
How do I load up or set up a wordlist path

**Comment by uxuf-khan225** [comment]
Same problem plz

**Comment by Rheed-pht** [comment]
wordlist path ?

**Comment by Bdhakerpc** [comment]
Please  world list path give me

**Comment by samsesh** [comment]
go to your wordlist dir and type this code 
```pwd```
and result is your wordlist dir path, you just add your wordlist name end of this , then copy path and  paste on script

**Comment by YusuF30sn30** [comment]
??

**Comment by Anon69-bit** [comment]
> go to your wordlist dir and type this code `pwd` and result is your wordlist dir path, you just add your wordlist name end of this , then copy path and paste on script

It's not working for me , 😭
