### ISSUE TITLE
Back menù bug

### ISSUE THREAD

**Issue by Lojacops** [samsesh/SocialBox-Termux#28]
When program says "Wanna back to the main menù (y/n)" if i chose n, the program exit, if i chose y, the programm install openssl.
How to fix it? It like this [https://www.reddit.com/r/termux/comments/ny58qo/no_i_dont_wanna_back_on_menù/?utm_source=share&utm_medium=web2x&context=3](url)

**Comment by samsesh** [comment]
@Ha3MrX

**Comment by samsesh** [comment]
fix it
