### ISSUE TITLE
error please fix it

### ISSUE THREAD

**Issue by dhanu7673** [samsesh/SocialBox-Termux#3]
`1.beta
                                                                       Select From Menu :

                 1 : Brute Force Facebook Account
                 2 : Brute Force Gmail Account
                 3 : Brute Force Instagram Account
                 4 : Brute Force Twitter Account
                 99: Exit
Choice >  1
                         Facebook Brute Force                         
Enter Facebook ID / Email / Username / Number: 9824204425
Enter wordlist path : /sdcard/psw.txt

Can't locate Net/SSLeay/Handle.pm in @INC (you may need to install the Net::SSLeay::Handle module) (@INC contains: /data/data/com.termux/files/usr/lib/perl5/site_perl/5.32.0/aarch64-android /data/data/com.termux/files/usr/lib/perl5/site_perl/5.32.0 /data/data/com.termux/files/usr/lib/perl5/5.32.0/aarch64-android /data/data/com.termux/files/usr/lib/perl5/5.32.0 .) at fb-brute.pl line 41.
BEGIN failed--compilation aborted at fb-brute.pl line 41.
                [+] Brute Force Complete [✓] [+]

Wanna Back To Main Menu [ Y / n ] : n

**Comment by samsesh** [comment]
install again and try
