### ISSUE TITLE
Twitter Bruteforce does not work!

### ISSUE THREAD

**Issue by chadofork** [samsesh/SocialBox-Termux#32]
I have used the twitter bruteforce with my own twitter account to see if it really works. I made my own password list with the correct pass within this .txt file and the script does not recognize it as the real pass. This script just does not work!
![tweet](https://user-images.githubusercontent.com/87623662/126514731-49cbdfa9-291e-4e4a-9c1e-5a790d74fe93.png)

**Comment by samsesh** [comment]
fix it
