### ISSUE TITLE
Brute force Instagram 2 didn't work

### ISSUE THREAD

**Issue by AJK000** [samsesh/SocialBox-Termux#39]
_Instagram Brute Force 2                                      [+] Service Tor Stated [+]
./SocialBox.sh: line 152: service: command not found
Traceback (most recent call last):                                              File "/data/data/com.termux/files/home/SocialBox-Termux/insta-bf/instabf.py", line 5, in <module>
    from six.moves import input
ModuleNotFoundError: No module named 'six'                                                   [+] Brute Force Complete [✓] [+]
./SocialBox.sh: line 155: service: command not found
                [+] Service Tor Stopped [+]
                                                                              Wanna Back To Main Menu [ Y / n ] :_

**Comment by samsesh** [comment]
run ```git pull``` and check again

**Comment by AJK000** [comment]
I run it and he show me same message

Choice >  5
                         Instagram Brute Force 2
        [+] Service Tor Started [+]
fail: start: unable to change to service directory: file does not exist
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/SocialBox-Termux/insta-bf/instabf.py", line 3, in <module>
    import requests, sys, threading, time, os, random
ModuleNotFoundError: No module named 'requests'
               [+] Brute Force Complete [✓] [+]
fail: stop: unable to change to service directory: file does not exist
                [+] Service Tor Stopped [+]

Wanna Back To Main Menu [ Y / n ] :
